FROM nginx:latest

# Set the working directory within the container
WORKDIR /usr/share/nginx/html

# Copy the entire SKIPPY directory into the container's web directory
COPY SKIPPY/ .

# Expose port 80 (standard web server port)
EXPOSE 80
